services:
  backend:
    image: maven:3.9-eclipse-temurin-17
    working_dir: /workspace
    entrypoint: ["sh","/workspace/dev-hot-reload.sh"]
    volumes:
      - ./Backend:/workspace
      - ~/.m2:/root/.m2
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_ADDRESS=0.0.0.0

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
